### ISSUE TITLE
[Todo] smc5.c.ll과 smc8.c.ll에서 bitset.set에서 첨자 범위 오류

### ISSUE THREAD

**Issue by kwanghoon** [JNU-SoftwareLAB/SMC-Bench#33]
[Todo] smc5.c.ll과 smc8.c.ll에서 bitset.set에서 첨자 범위 오류로 분석기 프로그램이 비정상 종료되는 문제

**Comment by dbwodlf3** [comment]
https://github.com/JNU-SoftwareLAB/SMC-Bench/blob/master/src/tools/constrainter/include/CubicSolver.hpp#L21
bitset 의 크기가 작아서 발생하는 문제.

임시방편으로 그 크기를 1000으로 늘렸습니다. 이 때에 정상적으로 작동했습니다.
추후에 동적으로 할당받을 수 있도록 업데이트 하겠다고 합니다.

**Comment by kwanghoon** [comment]
bitset length를 분석기에서 미리 계산해서
큐빅 알고리즘 측에 넘겨주면
그 이후로 알고리즘에서는 이 계산된 length를 사용하도록 변경해야 하는 것 아닌가?
성호하고 이야기해봐.
지금은 분석기 완성도를 올리는데 시간이 급하니 일단 1000으로 올려 진행하고.

**Comment by dbwodlf3** [comment]
예.

**Comment by dbwodlf3** [comment]
성호와 이야기를 해보았는데.
bitset 에서 dynamic_bitset 으로 변경해야 한다고 합니다.
이 때에 method들이 동일하지 않아서 수정하기가 어렵다고 합니다.

**Comment by kwanghoon** [comment]
어떤 상황인지는 잘 이해했고.
처음 시작할 때 bit set 길이를 한 번만 지정하고
이후에는 동일한 길이의 bit set들을 사용하면 되는데.

dynamic bitset은 큐빅 알고리즘이 동작하면서
늘리고 줄이고 하는 bitset으로 보인다. 
그런 기능까지는 필요하지 않아.

**Comment by dbwodlf3** [comment]
컴파일타임에 bitset의 길이가 지정이 된다고 합니다.

**Comment by dbwodlf3** [comment]
다시한번 확인해보도록 하겠습니다..

**Comment by kwanghoon** [comment]
:+1:
